versions:
  - caddy_version: '2.11.2'
    is_major: true
    is_latest: true

xcaddy_config:
  version: '0.4.5'
  checksums:
    amd64: edea47d552fd9ac0a533386a72acaa95733ce734f347c11e5513469b5dc0eec0a62a6e21cfa93a83ab00b2dad72e0ee0b9bdf267a9654235f70d4c934739a15b
    arm64v8: 2933968a6e759a0406dc864000960fe0e605db9f0fe0662ce245897eaa5b529e322d1b14c2b98463a95e13f1dfd85432541b41f459a237daedb8c68a8f6a5bb1
  with:
    - github.com/caddy-dns/loopia
    - github.com/caddy-dns/glesys

# configuration for the stackbrew.tmpl template
variants:
  - dir: alpine
    tags: [ "alpine" ]
    shared_tags: [ "latest" ]
    architectures: [ amd64, arm64v8 ]
    base: FROM golang:1.26-alpine

images:
  - name: "kmpm/caddy"
    token_env: DOCKER_TOKEN
    user_env: DOCKER_USER
  - name: "ghcr.io/kmpm/caddy"
    token_env: GITHUB_TOKEN
    user_env: GITHUB_USER


