versions:
  - caddy_version: '2.11.4'
    is_major: true
    is_latest: true

xcaddy_config:
  version: '0.4.7'
  checksums:
    amd64: 99fd895a7b7799b18c43ea0915777d8701aaab2a010035b23495c28b4ae429edccd70adb9a01106180f8d9333d9b5df41e74f9702ce0e1cffcf8840698a9ab93
    arm64v8: b4d52ad6db4184fa5366ef225d24b8340a47fc1924d250b329d3b95f416a0b14e16d72cf71f04f57046e8a26bad2b697ac14c833fc5f5607b9e1c838b9898520
  with:
    - github.com/caddy-dns/loopia
    - github.com/caddy-dns/glesys

# configuration for the stackbrew.tmpl template
variants:
  - dir: alpine
    tags: [ "alpine" ]
    shared_tags: [ "latest" ]
    architectures: [ amd64, arm64v8 ]
    base: FROM golang:1.26-alpine

images:
  - name: "kmpm/caddy"
    token_env: DOCKER_TOKEN
    user_env: DOCKER_USER
  - name: "ghcr.io/kmpm/caddy"
    token_env: GITHUB_TOKEN
    user_env: GITHUB_USER


